esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

i2c:
  sda: GPIO15
  scl: GPIO16
  scan: true
  id: I2C

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

output:
  - platform: ledc
    pin: GPIO33
    frequency: 19531Hz
    id: LED_channel_1

  - platform: ledc
    pin: GPIO32
    frequency: 19531Hz
    id: LED_channel_2

  - platform: ledc
    pin: GPIO12
    frequency: 19531Hz
    id: LED_channel_3

  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: LED_channel_4

  - platform: ledc
    pin: GPIO2
    frequency: 19531Hz
    id: LED_channel_5