# TODO: make this a proper external component
#external_components:
#  - source:
#      type: git
#      url: https://github.com/markusressel/CustomRGBWLight
#      ref: master
#    components: [ ColorTempRGBWLight ]

esphome:
  includes:
    - src/ColorTempRGBWLight.h

light:
  - platform: custom
    lambda: |-
      auto light = new CustomRGBWLight(id(LED_channel_2), id(LED_channel_3), id(LED_channel_4), id(LED_channel_1));
      App.register_component(light);
      return {light};
    lights:
      - name: "Light"
        id: light_entity
        default_transition_length: 1s
        on_turn_on:
          then:
            - globals.set:
                id: current_light_on_state
                value: 'true'
            - if:
                condition:
                  - lambda: 'return id(state_user_override_active).state == false;'
                then:
                  # relevant for manual light control only, might cause flickering
                  - script.execute: update_cycle_stage
                  - script.execute: apply_light_props
        on_turn_off:
          then:
            - globals.set:
                id: current_light_on_state
                value: 'false'
